# Generated by Django 4.0.5 on 2022-07-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='days',
            field=models.PositiveIntegerField(default=28),
        ),
    ]
