# Generated by Django 4.0.5 on 2022-07-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0002_frequency_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='time',
        ),
        migrations.AddField(
            model_name='frequency',
            name='frequency',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequency',
            name='name',
            field=models.CharField(default=' ', max_length=64),
            preserve_default=False,
        ),
    ]
