# Generated by Django 4.0.5 on 2022-07-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0003_remove_frequency_time_frequency_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequency',
            old_name='frequency',
            new_name='time',
        ),
    ]
