# Generated by Django 4.0.5 on 2022-07-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0004_rename_frequency_frequency_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='time',
        ),
    ]
