# Generated by Django 4.0.5 on 2022-07-10 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0005_remove_frequency_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='frequency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Subscriptions.frequency'),
        ),
    ]
