# Generated by Django 4.0.5 on 2022-07-23 21:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0006_alter_subscription_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='amount_currency',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
