# Generated by Django 4.0.5 on 2022-07-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0010_frequency_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='slug',
        ),
    ]
