# Generated by Django 4.0.5 on 2022-07-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0011_remove_frequency_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
